apiVersion: v1
kind: Pod
metadata:
  name: pod-passing-metadata-env
spec:
  containers:
  - image: abdas81/k8s-metadata
    name: container-passing-metadata-env
    ports:
    - containerPort: 1222
      protocol: TCP
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP_ADDRESS
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName