apiVersion: v1
kind: Pod
metadata:
  name: pod-passing-config-volume
spec:
  containers:
    - image: nginx:alpine
      name: container-nginx-alpine-config-volume
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: my-config