apiVersion: v1
kind: Pod
metadata:
  name: pod-passing-config-configmap
spec:
  containers:
  - image: abdas81/mock-http-req-status:env
    name: container-passing-cofig-configmap
    env:
      - name: NUMBER_OF_200
        valueFrom:
          configMapKeyRef:
            name: configmap-for-cluster
            key: NUMBER_OF_200
    livenessProbe:
        httpGet:
          path: /
          port: 1221