apiVersion: v1
kind: Pod
metadata:
  name: pod-passing-metadata-downward-volume
  labels:
    author: AbhishekDas
    position: DevOpsEngineer
  annotations:
    objective-1: single line annotation
    objective-2: |
      multiple
      line
      annotation
spec:
  containers:
  - image: abdas81/k8s-metadata
    name: container-passing-metadata-downward-volume
    ports:
    - containerPort: 1222
      protocol: TCP
    volumeMounts:
    - name: downward
      mountPath: /etc/downward
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP_ADDRESS
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels
      - path: annotations
        fieldRef:
         fieldPath: metadata.annotations